// ========== standard metadata (default for new Next.js project)
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    absolute: '', // if set, it template is ignored
    default: 'Next.js Tutorial - Codevolution',
    template: '%s | Codevolution',
    // compare to /blog/page.tsx
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <header style={{ backgroundColor: 'lightblue', padding: '1rem' }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: 'ghostwhite', padding: '1rem' }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
